const READ_MENU_ID = "isabella-read-selection";
const STOP_MENU_ID = "isabella-stop";
const OFFSCREEN_DOCUMENT = "offscreen.html";

let creatingOffscreenDocument = null;

chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.removeAll(() => {
    chrome.contextMenus.create({
      id: READ_MENU_ID,
      title: "Read selection with Isabella",
      contexts: ["selection"],
    });

    chrome.contextMenus.create({
      id: STOP_MENU_ID,
      title: "Stop Isabella",
      contexts: ["page", "selection"],
    });
  });
});

async function ensureOffscreenDocument() {
  const offscreenUrl = chrome.runtime.getURL(OFFSCREEN_DOCUMENT);

  const existingContexts = await chrome.runtime.getContexts({
    contextTypes: ["OFFSCREEN_DOCUMENT"],
    documentUrls: [offscreenUrl],
  });

  if (existingContexts.length > 0) {
    return;
  }

  if (!creatingOffscreenDocument) {
    creatingOffscreenDocument = chrome.offscreen.createDocument({
      url: OFFSCREEN_DOCUMENT,
      reasons: ["AUDIO_PLAYBACK"],
      justification: "Play speech generated by the user's local Kokoro server.",
    }).finally(() => {
      creatingOffscreenDocument = null;
    });
  }

  await creatingOffscreenDocument;
}

chrome.contextMenus.onClicked.addListener(async (info) => {
  try {
    await ensureOffscreenDocument();

    if (info.menuItemId === READ_MENU_ID) {
      const text = (info.selectionText ?? "").trim();

      if (!text) {
        return;
      }

      await chrome.runtime.sendMessage({
        target: "offscreen",
        type: "ISABELLA_SPEAK",
        text,
      });
    }

    if (info.menuItemId === STOP_MENU_ID) {
      await chrome.runtime.sendMessage({
        target: "offscreen",
        type: "ISABELLA_STOP",
      });
    }
  } catch (error) {
    console.error("Isabella Local Reader:", error);
  }
});
